# Generated by Django 3.0.8 on 2021-06-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
