# Generated by Django 3.0.8 on 2021-06-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttodo',
            old_name='completed',
            new_name='Completed',
        ),
        migrations.RenameField(
            model_name='posttodo',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='posttodo',
            old_name='userId',
            new_name='UserId',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='Completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='userId',
            new_name='UserId',
        ),
    ]
